"""deliveries module

Revision ID: 046e51604147
Revises: 03e7240d1e2d
Create Date: 2026-09-21 10:08:33.646505
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '046e51604147'
down_revision: Union[str, None] = '03e7240d1e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('pickup_location', sa.String(length=500), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('dropoff_location', sa.String(length=500), nullable=False),
    sa.Column('dropoff_lat', sa.Float(), nullable=True),
    sa.Column('dropoff_lng', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_customer_id'), 'deliveries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=False)
    op.create_index(op.f('ix_deliveries_organization_id'), 'deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_table('delivery_status_history',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_status_history_created_at'), 'delivery_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_delivery_status_history_delivery_id'), 'delivery_status_history', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_status_history_organization_id'), 'delivery_status_history', ['organization_id'], unique=False)
    op.create_table('packages',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('length', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('width', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('height', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('volume', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_packages_org_code')
    )
    op.create_index(op.f('ix_packages_code'), 'packages', ['code'], unique=False)
    op.create_index(op.f('ix_packages_delivery_id'), 'packages', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_packages_organization_id'), 'packages', ['organization_id'], unique=False)
    op.create_table('proof_of_delivery',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signature_s3_key', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_of_delivery_delivery_id'), 'proof_of_delivery', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_proof_of_delivery_organization_id'), 'proof_of_delivery', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proof_of_delivery_organization_id'), table_name='proof_of_delivery')
    op.drop_index(op.f('ix_proof_of_delivery_delivery_id'), table_name='proof_of_delivery')
    op.drop_table('proof_of_delivery')
    op.drop_index(op.f('ix_packages_organization_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_delivery_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_code'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_delivery_status_history_organization_id'), table_name='delivery_status_history')
    op.drop_index(op.f('ix_delivery_status_history_delivery_id'), table_name='delivery_status_history')
    op.drop_index(op.f('ix_delivery_status_history_created_at'), table_name='delivery_status_history')
    op.drop_table('delivery_status_history')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_organization_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_customer_id'), table_name='deliveries')
    op.drop_table('deliveries')
    # ### end Alembic commands ###