"""warehouse module

Revision ID: b11908f7a541
Revises: 7377555911c0
Create Date: 2026-09-21 08:40:23.627437
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b11908f7a541'
down_revision: Union[str, None] = '7377555911c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_warehouses_org_code')
    )
    op.create_index(op.f('ix_warehouses_organization_id'), 'warehouses', ['organization_id'], unique=False)
    op.create_table('warehouse_tasks',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_tasks_organization_id'), 'warehouse_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_warehouse_tasks_status'), 'warehouse_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_warehouse_tasks_type'), 'warehouse_tasks', ['type'], unique=False)
    op.create_index(op.f('ix_warehouse_tasks_warehouse_id'), 'warehouse_tasks', ['warehouse_id'], unique=False)
    op.create_table('zones',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_zones_warehouse_code')
    )
    op.create_index(op.f('ix_zones_organization_id'), 'zones', ['organization_id'], unique=False)
    op.create_index(op.f('ix_zones_warehouse_id'), 'zones', ['warehouse_id'], unique=False)
    op.create_table('locations',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'code', name='uq_locations_zone_code')
    )
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_locations_zone_id'), 'locations', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_zone_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_zones_warehouse_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_organization_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_warehouse_tasks_warehouse_id'), table_name='warehouse_tasks')
    op.drop_index(op.f('ix_warehouse_tasks_type'), table_name='warehouse_tasks')
    op.drop_index(op.f('ix_warehouse_tasks_status'), table_name='warehouse_tasks')
    op.drop_index(op.f('ix_warehouse_tasks_organization_id'), table_name='warehouse_tasks')
    op.drop_table('warehouse_tasks')
    op.drop_index(op.f('ix_warehouses_organization_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###