"""domain events outbox

Revision ID: b4c3fd57aefe
Revises: e14d3ab20f02
Create Date: 2026-09-21 10:50:44.371634
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b4c3fd57aefe'
down_revision: Union[str, None] = 'e14d3ab20f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_aggregate_id'), 'domain_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_domain_events_created_at'), 'domain_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_events_organization_id'), 'domain_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_domain_events_published_at'), 'domain_events', ['published_at'], unique=False)
    op.create_index('ix_domain_events_published_created', 'domain_events', ['published_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_domain_events_type'), 'domain_events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_events_type'), table_name='domain_events')
    op.drop_index('ix_domain_events_published_created', table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_published_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_organization_id'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_created_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_aggregate_id'), table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###