"""dispatch module

Revision ID: bc44d3ddf192
Revises: cace03edb0a2
Create Date: 2026-09-21 10:15:56.633830
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bc44d3ddf192'
down_revision: Union[str, None] = 'cace03edb0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_delivery_id'), 'assignments', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_assignments_driver_id'), 'assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_assignments_organization_id'), 'assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('dispatch_events',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('candidate_driver_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('factors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_events_created_at'), 'dispatch_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_dispatch_events_delivery_id'), 'dispatch_events', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_dispatch_events_organization_id'), 'dispatch_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_events_organization_id'), table_name='dispatch_events')
    op.drop_index(op.f('ix_dispatch_events_delivery_id'), table_name='dispatch_events')
    op.drop_index(op.f('ix_dispatch_events_created_at'), table_name='dispatch_events')
    op.drop_table('dispatch_events')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_organization_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_driver_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_delivery_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###