"""tracking events + public token

Revision ID: d0247e52ba3f
Revises: fc0448967b51
Create Date: 2026-09-22 04:25:02.537409
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd0247e52ba3f'
down_revision: Union[str, None] = 'fc0448967b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_events',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_created_at'), 'tracking_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_events_delivery_id'), 'tracking_events', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_organization_id'), 'tracking_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_type'), 'tracking_events', ['type'], unique=False)
    op.add_column('deliveries', sa.Column('public_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_deliveries_public_token'), 'deliveries', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_public_token'), table_name='deliveries')
    op.drop_column('deliveries', 'public_token')
    op.drop_index(op.f('ix_tracking_events_type'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_organization_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_delivery_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_created_at'), table_name='tracking_events')
    op.drop_table('tracking_events')
    # ### end Alembic commands ###