"""analytics module

Revision ID: e14d3ab20f02
Revises: 58cfffc1b27c
Create Date: 2026-09-21 10:43:39.021320
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e14d3ab20f02'
down_revision: Union[str, None] = '58cfffc1b27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_deliveries_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('deliveries_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('avg_duration_s', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', name='uq_fact_deliv_org_date')
    )
    op.create_index(op.f('ix_fact_deliveries_daily_date'), 'fact_deliveries_daily', ['date'], unique=False)
    op.create_index(op.f('ix_fact_deliveries_daily_organization_id'), 'fact_deliveries_daily', ['organization_id'], unique=False)
    op.create_table('fact_driver_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('deliveries_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', 'driver_id', name='uq_fact_driver_org_date_drv')
    )
    op.create_index(op.f('ix_fact_driver_daily_date'), 'fact_driver_daily', ['date'], unique=False)
    op.create_index(op.f('ix_fact_driver_daily_driver_id'), 'fact_driver_daily', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fact_driver_daily_organization_id'), 'fact_driver_daily', ['organization_id'], unique=False)
    op.create_table('fact_inventory_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('low_stock_flag', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', 'product_id', 'warehouse_id', name='uq_fact_inv_org_date_prod_wh')
    )
    op.create_index(op.f('ix_fact_inventory_daily_date'), 'fact_inventory_daily', ['date'], unique=False)
    op.create_index(op.f('ix_fact_inventory_daily_organization_id'), 'fact_inventory_daily', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fact_inventory_daily_product_id'), 'fact_inventory_daily', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_inventory_daily_warehouse_id'), 'fact_inventory_daily', ['warehouse_id'], unique=False)
    op.create_table('fact_orders_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('cancelled_count', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', name='uq_fact_orders_org_date')
    )
    op.create_index(op.f('ix_fact_orders_daily_date'), 'fact_orders_daily', ['date'], unique=False)
    op.create_index(op.f('ix_fact_orders_daily_organization_id'), 'fact_orders_daily', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_orders_daily_organization_id'), table_name='fact_orders_daily')
    op.drop_index(op.f('ix_fact_orders_daily_date'), table_name='fact_orders_daily')
    op.drop_table('fact_orders_daily')
    op.drop_index(op.f('ix_fact_inventory_daily_warehouse_id'), table_name='fact_inventory_daily')
    op.drop_index(op.f('ix_fact_inventory_daily_product_id'), table_name='fact_inventory_daily')
    op.drop_index(op.f('ix_fact_inventory_daily_organization_id'), table_name='fact_inventory_daily')
    op.drop_index(op.f('ix_fact_inventory_daily_date'), table_name='fact_inventory_daily')
    op.drop_table('fact_inventory_daily')
    op.drop_index(op.f('ix_fact_driver_daily_organization_id'), table_name='fact_driver_daily')
    op.drop_index(op.f('ix_fact_driver_daily_driver_id'), table_name='fact_driver_daily')
    op.drop_index(op.f('ix_fact_driver_daily_date'), table_name='fact_driver_daily')
    op.drop_table('fact_driver_daily')
    op.drop_index(op.f('ix_fact_deliveries_daily_organization_id'), table_name='fact_deliveries_daily')
    op.drop_index(op.f('ix_fact_deliveries_daily_date'), table_name='fact_deliveries_daily')
    op.drop_table('fact_deliveries_daily')
    # ### end Alembic commands ###