"""password reset tokens

Revision ID: fc0448967b51
Revises: ba9ee7fabaef
Create Date: 2026-09-21 12:54:28.181156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc0448967b51'
down_revision: Union[str, None] = 'ba9ee7fabaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###